### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Solaire** [Nutzzz/GLC#12]
There should be a nice piece of documentation describing the overall app functionality, some technical stuff for more complex pieces of code as well as the usage (so the supported commands and key-bindings).

We should probably use GitHub's wiki feature

**Comment by Nutzzz** [comment]
In my fork, I've moved a lot of the information out of the README.md and put it into the starting point for a wiki: https://github.com/Nutzzz/GLC/wiki

**Comment by Nutzzz** [comment]
Oops, it looks like you missed my note in the last pull request (and the comment above).  A recent edit to README.MD links to a wiki.  You can use my fork as a starting point, or I'd be happy to put it together once you create it.  Or you can just remove that section from README.MD.

**Comment by Solaire** [comment]
I have migrated the wiki over to this repo. Will continue to add extra things (such as contribution, technical details, etc) as the development goes on.

**Comment by Solaire** [comment]
Closing issue as the original thing was resolved (create wiki)
