### ISSUE TITLE
Small issue with 1.1.0 release description

### ISSUE THREAD

**Issue by Nutzzz** [Nutzzz/GLC#16]
In the description of 1.1.0 release, it mentions "/" is the default key to switch to insert mode.  Actually, "\\" switches to insert mode, while "/" (or F3) does a search (the latter being much better at the moment since it does fuzzy searches).

**Comment by Solaire** [comment]
Updated. Thank you for pointing it out

**Comment by Nutzzz** [comment]
Oops, you actually need to escape "\\" in the description by doubling up on the backslashes ("\\\\").  I had the same problem in the bug report.

**Comment by Solaire** [comment]
Well spotted. I guess even markdown isn't safe. Fixed.
