### ISSUE TITLE
Support for multiple Steam folder location

### ISSUE THREAD

**Issue by samuelmichaud** [Nutzzz/GLC#62]
Tested on the version *1.1.0.0*
*I'm sorry for not testing it on a newer version but the 1.2.0.0 is no more standalone (https://github.com/Solaire/GLC/issues/58) and don't work on my machine anymore*

**Is your feature request related to a problem? Please describe.**
Steam allows to use multiple folders for installing & storing games.
If I'm not mistaking, GLC scan only for the first one so games from the second (or third, ...) location are never found.

In the Steam UI, you can find it in settings > Download :  
![image](https://user-images.githubusercontent.com/807909/200184966-79ecf220-d12a-4259-8c19-bc32e9b13023.png)

In the system file, the information can be found (and parse) here : 

```
C:\Program Files (x86)\Steam\config\libraryfolders.vdf
```

**Describe the solution you'd like**
I would like that GLC scan all Steam folders so no games are left behind :)

EDIT : 
Reading this file : https://github.com/Solaire/GLC/blob/c5223ce1ad9aa5e4c181288d85c5166ae2a6d7a2/GameLauncher_Console/GameLauncher_Console/Platforms/Steam.cs#L122 I guess the case should be handled.

When looking for the logs, I saw that : 

```
06/11/2022 18:00:49 : ERROR: La clé donnée était absente du dictionnaire. | mscorlib    à System.ThrowHelper.ThrowKeyNotFoundException()
   à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à GameLauncher_Console.CRegScanner.GetSteamGames(List`1 gameDataList, Boolean expensiveIcons) | ERROR: Malformed STEAM file: C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf
```

Might be another issue then... don't hesitate to close this one if not appropriate.

Many thanks for your hard work! 🙌

**Comment by Nutzzz** [comment]
Yes, that's been in there for quite a while [on v1.2]. I used to have multiple locations on my PC; I don't anymore, so of course let me know if there's been a regression.

I'm not sure why Publish isn't working for @Solaire (he never fully described the issue), but note I've posted a number of v1.2 alpha binaries in [my fork](/Nutzzz/GLC/releases). I'll upload the latest tonight (assuming I remember).

**Comment by Nutzzz** [comment]
[1.2.0-alpha14](https://github.com/Nutzzz/GLC/releases/tag/1.2.0-alpha14) has been published in my fork.

**Comment by samuelmichaud** [comment]
I've seen that! Big thanks. I'm closing this issue since I'm pretty sure it does work and the real issue is more tied to a specific game.
Will test it on 1.2 alpha and open another one if still crash and if I see stuff in logs.
